# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 01:25
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HaskerAnswer',
            fields=[
                ('_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('text', models.TextField()),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HaskerQuestion',
            fields=[
                ('_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('title', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HaskerTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.SlugField(max_length=32, unique=True)),
                ('question', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hasker_main.HaskerQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='HaskerUser',
            fields=[
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('picture', models.ImageField(blank=True, upload_to='hasker_main/static/profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
