# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasker_main', '0003_auto_20170813_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haskerquestion',
            name='tags',
            field=models.ManyToManyField(max_length=3, to='hasker_main.HaskerTag'),
        ),
    ]
